apiVersion: v1
kind: Service
metadata:
  name: flask-webhook-service
  labels:
    env: prod
    app: flask-webhook    
spec:
  selector:
    app: flask-webhook
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
