apiVersion: v1
kind: Service
metadata:
  name: flask-webhook-service-{{ .Release.Name }}
  labels:
    env: {{ .Values.container.env }}
    app: flask-webhook-{{ .Release.Name }}
spec:
  selector:
    app: flask-webhook-{{ .Release.Name }}
  ports:
    - protocol: TCP
      {{- if eq .Values.container.env "stage" }}
      port: {{ .Values.container.stagePort }}
      {{- else }}
      port: {{ .Values.container.prodPort }}                                      
      {{- end }}
      targetPort: 5000
